name: Node.js Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies and run tests
        run: npm install

      - name: Build project assets
        run: npm run build

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: dist/
